version: '3.8'
services:
  # Generic CPU-only server
  cpu-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - SERVER_NAME=CPU-Server
    command: ["python3", "main.py", "--host", "0.0.0.0", "--port", "8765", "--name", "CPU-Server"]

  # NVIDIA GPU-accelerated server
  nvidia-server:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    ports:
      - "8766:8765"
    environment:
      - SERVER_NAME=NVIDIA-Server
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python3", "main.py", "--host", "0.0.0.0", "--port", "8765", "--name", "NVIDIA-Server"]

  # Intel QSV-accelerated server
  intel-server:
    build:
      context: .
      dockerfile: Dockerfile.intel
    ports:
      - "8767:8765"
    environment:
      - SERVER_NAME=Intel-Server
    devices:
      - "/dev/dri:/dev/dri" # Pass through the Direct Rendering Infrastructure device
    command: ["python3", "main.py", "--host", "0.0.0.0", "--port", "8765", "--name", "Intel-Server"]
